export enum TabEvents {
  LOAD_URL = "LOAD_URL",
  CREATE_TAB = "CREATE_TAB",
  DELETE_TAB = "DELETE_TAB",
  FOCUS_TAB = "FOCUS_TAB",
  RELOAD_TAB = "RELOAD_TAB",
  FETCH_TABS = "FETCH_TABS",
  CANCEL_TAB_NAVIGATION = "CANCEL_TAB_NAVIGATION",
  NAVIGATE_TAB_FORWARD = "NAVIGATE_TAB_FORWARD",
  NAVIGATE_TAB_BACKWARD = "NAVIGATE_TAB_BACKWARD",
}

export enum SearchEvents {
  LOAD_URL = "LOAD_URL",
  SHOW_SEARCH = "SHOW_SEARCH",
  HIDE_SEARCH = "HIDE_SEARCH",
  UPDATE_SEARCH_QUERY = "UPDATE_SEARCH_QUERY",
}

export enum SearchRendererEvents {
  SEARCH_QUERY_UPDATED = "SEARCH_QUERY_UPDATED",
}

export enum RendererEvents {
  TAB_LOAD_START = "TAB_LOAD_START",
  TAB_LOAD_STOP = "TAB_LOAD_STOP",
  TAB_CREATED = "TAB_CREATED",
  TAB_DELETED = "TAB_DELETED",
  TAB_FOCUSED = "TAB_FOCUSED",
  FINISH_LOAD = "FINISH_LOAD",
  TAB_TITLE_CHANGED = "TAB_TITLE_CHANGED",
  TAB_THEME_COLOR_CHANGED = "TAB_THEME_COLOR_CHANGED",
  TAB_NAVIGATION_STATE_CHANGED = "TAB_NAVIGATION_STATE_CHANGED",
}
