
# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Configure Fontawesome
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: .npmrc
          contents: "\n//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}\n//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_TOKEN }}"
          write-mode: append
      - run: cat .npmrc
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "6.x"
          run_install: true
      - run: pnpm build:release
